server:
  port: 8086
spring: 
  datasource:
   url: jdbc:mysql://localhost:3306/poc_4
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
